services:
  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app
    command: python app.py
    container_name: flask-2
